import Head from 'next/head';
import Header from './components/Header';
import Library from './components/Library';
import Informative from "./components/Informative";
import Footer from './components/Footer';

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Leadster</title>
        <meta name="description" content="Leadster - Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Library list={data} />
      <Informative />
      <Footer />
    </>
  );
}

export async function getStaticProps() {
  const response = await fetch('http://localhost:3000/api/library');
  const data = await response.json();

  return {
    props: { data }
  };
}
